version: '3.8'

x-airflow-common:
  &airflow-common
  build:
    context: .
    dockerfile: ./airflow/Dockerfile
  image: rag/airflow:latest
  environment:
    &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-postgres/airflow
    AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-postgres/airflow
    AIRFLOW__CORE__FERNET_KEY: ''
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__API__AUTH_BACKENDS: 'airflow.api.auth.backend.basic_auth,airflow.api.auth.backend.session'
    AIRFLOW__SCHEDULER__ENABLE_HEALTH_CHECK: 'true'
    AIRFLOW__SCHEDULER__STATSD_ON: 'true'
    AIRFLOW__SCHEDULER__STATSD_HOST: statsd-exporter
    AIRFLOW__SCHEDULER__STATSD_PORT: 8125
    AIRFLOW__SCHEDULER__STATSD_PREFIX: airflow
    DBT_PROFILES_DIR: /home/codespace/.dbt  # Added for DBT
    DBT_PROJECT_DIR: /opt/airflow/dbt       # Added for DBT
    _PIP_ADDITIONAL_REQUIREMENTS: ${_PIP_ADDITIONAL_REQUIREMENTS:-}
  volumes:
    - ./airflow/dags:/opt/airflow/dags
    - ./airflow/logs:/opt/airflow/logs
    - ./airflow/config:/opt/airflow/config
    - ./airflow/plugins:/opt/airflow/plugins
    - ./airflow/data:/opt/airflow/data
    - ./dbt:/opt/airflow/dbt              # Added for DBT project
    - /home/codespace/.dbt:/home/codespace/.dbt  # Added for DBT profiles
  user: "${AIRFLOW_UID:-50000}:0"
  networks:
    - airflow-network
  depends_on:
    &airflow-common-depends-on
    airflow-postgres:
      condition: service_healthy
    datawarehouse:
      condition: service_healthy

services:
  # Data Warehouse and Analytics Services
  datawarehouse:
    image: postgres:13
    container_name: dw_postgres
    environment:
      - POSTGRES_USER=${DW_POSTGRES_USER}
      - POSTGRES_PASSWORD=${DW_POSTGRES_PASSWORD}
      - POSTGRES_DB=${DW_DATABASE_NAME}
    volumes:
      - "./dw_postgres_data:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DW_POSTGRES_USER} -d ${DW_DATABASE_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - airflow-network

  pgadmin-management:
    image: dpage/pgadmin4
    container_name: dw_pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${DW_ADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${DW_ADMIN_PASSWORD}
    ports:
      - "5050:80"
    restart: unless-stopped
    depends_on:
      - datawarehouse
    networks:
      - airflow-network

  metabase:
    image: metabase/metabase:latest
    container_name: dw_metabase
    ports:
      - "3000:3000"
    volumes:
      - metabase_data:/metabase
    environment:
      - MB_DB_TYPE=postgres
      - MB_DB_DBNAME=${DW_DATABASE_NAME}
      - MB_DB_PORT=5432
      - MB_DB_USER=${DW_POSTGRES_USER}
      - MB_DB_PASS=${DW_POSTGRES_PASSWORD}
      - MB_DB_HOST=datawarehouse
    depends_on:
      - datawarehouse
    restart: unless-stopped
    networks:
      - airflow-network

  # Airflow Services
  airflow-postgres:
    image: postgres:13
    container_name: airflow-postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - airflow-postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always
    networks:
      - airflow-network

  airflow-webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8974/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully

  airflow-init:
    <<: *airflow-common
    entrypoint: /bin/bash
    command:
      - -c
      - |
        mkdir -p /opt/airflow/{logs,dags,plugins,config,data}
        chown -R "${AIRFLOW_UID}:0" /opt/airflow
        exec /entrypoint airflow version
    environment:
      <<: *airflow-common-env
      _AIRFLOW_DB_MIGRATE: 'true'
      _AIRFLOW_WWW_USER_CREATE: 'true'
      _AIRFLOW_WWW_USER_USERNAME: ${_AIRFLOW_WWW_USER_USERNAME:-airflow}
      _AIRFLOW_WWW_USER_PASSWORD: ${_AIRFLOW_WWW_USER_PASSWORD:-airflow}
    user: "0:0"
    volumes:
      - ./airflow:/opt/airflow

  # Monitoring Services
  statsd-exporter:
    image: prom/statsd-exporter
    container_name: statsd-exporter
    command: "--statsd.listen-udp=:8125 --web.listen-address=:9102"
    ports:
      - "9102:9102"
      - "8125:8125/udp"
    networks:
      - airflow-network

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - --log.level=debug
      - --web.listen-address=:9090
      - --web.page-title='Prometheus - Airflow Metrics'
    networks:
      - airflow-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/volume/data:/grafana
      - ./grafana/provisioning:/grafana/provisioning
      - ./grafana/volume/datasources:/grafana/datasources
      - ./grafana/volume/dashboards:/grafana/dashboards
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD:-admin}
      GF_PATHS_PROVISIONING: /grafana/provisioning
    networks:
      - airflow-network

networks:
  airflow-network:
    driver: bridge

volumes:
  airflow-postgres-db-volume:
  grafana_data:
  metabase_data: