version: '3'

services:
  datawarehouse:
    image: postgres:13
    container_name: dw_postgres
    environment:
      - POSTGRES_USER=${DW_POSTGRES_USER}
      - POSTGRES_PASSWORD=${DW_POSTGRES_PASSWORD}
      - POSTGRES_DB=${DW_DATABASE_NAME}
    volumes:
      - "./dw_postgres_data:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DW_POSTGRES_USER} -d ${DW_DATABASE_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin-management:
    image: dpage/pgadmin4
    container_name: dw_pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${DW_ADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${DW_ADMIN_PASSWORD}
    ports:
      - "8080:80"
    restart: unless-stopped
    depends_on:
      - datawarehouse

  metabase:
    image: metabase/metabase:latest
    container_name: dw_metabase
    ports:
      - "3000:3000"
    volumes:
      - metabase_data:/metabase
    environment:
      - MB_DB_TYPE=postgres
      - MB_DB_DBNAME=${DW_DATABASE_NAME}
      - MB_DB_PORT=5432
      - MB_DB_USER=${DW_POSTGRES_USER}
      - MB_DB_PASS=${DW_POSTGRES_PASSWORD}
      - MB_DB_HOST=datawarehouse
    depends_on:
      - datawarehouse
    restart: unless-stopped

volumes:
  metabase_data: